### ISSUE TITLE
mqtt publish消息中的message id为0的问题

### ISSUE THREAD

**Issue by linrx1511** [PandoCloud/tisan-demo-rgb-led#36]
在plug的demo中，控制继电器时服务器下发的mqtt publish消息中的id有点问题，id = 0x0000,mqtt标准不应该是0的！不知道是此固件显示问题，还是云平台下发数据有问题。

**Comment by ruizeng** [comment]
感谢反馈，是服务器端程序的问题，已经进行了修改。
